apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
    containers:
        - name: nginx
          image: nginx
          {{- if gt ( len .Values.configMapFromFiles ) 0 }}
          volumeMounts:
          {{- range $cm := .Values.configMapFromFiles }}
            - name: {{ $cm.name }}
              mountPath: {{ $cm.mount }}
          {{- end }}
          {{- end }}
    {{- if gt ( len .Values.configMapFromFiles ) 0 }}
    volumes:
        {{- range $cm := .Values.configMapFromFiles }}
        - name: {{ $cm.name }}
          configMap:
            name: {{ $cm.name }}
        {{- end }}
    {{- end }}
