apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-bluegreen.fullname" . }}-active
  labels:
    {{- include "argocd-bluegreen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "argocd-bluegreen.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-bluegreen.fullname" . }}-preview
  labels:
    {{- include "argocd-bluegreen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "argocd-bluegreen.selectorLabels" . | nindent 4 }}
