apiVersion: v1
kind: Service
metadata:
  name: "{{ include "argocd-canary.fullname" . }}-canary"
  labels:
    {{- include "argocd-canary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "argocd-canary.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "argocd-canary.fullname" . }}-stable"
  labels:
    {{- include "argocd-canary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "argocd-canary.selectorLabels" . | nindent 4 }}