{{- if .Values.argoRollout.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
spec:
  args:
  - name: query-service-name
  - name: prometheus-address
  - name: query-interval
    value: 1m
  - name: success-rate
    value: 95
  - name: metrics-interval
    value: 15s
  - name: metrics-failure-limit
    value: 3
  metrics:
  - name: success-rate
    interval: "{{`{{args.metrics-interval}}`}}"
    successCondition: result[0] >= "{{`{{args.success-rate}}`}}"
    failureLimit: "{{`{{args.metrics-failure-limit}}`}}"
    provider:
      prometheus:
        address: "{{`{{args.prometheus-address}}`}}"
        query: |
          (
            sum(irate(api_requests_latency_by_status_sum{service="{{`{{args.query-service-name}}`}}",status="200"}[{{`{{args.query-interval}}`}}])) /
            sum(irate(api_requests_latency_by_status_sum{service="{{`{{args.query-service-name}}`}}"}[{{`{{args.query-interval}}`}}]))
          ) * 100
{{- end }}
