{{- if .Values.argoRollout.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: "{{`{{args.prometheus-address}}`}}"
        query: |
          ( 
            sum(irate(api_requests_latency_by_status_count{service="{{`{{args.service-name}}`}}",status="500"}[5m])) / 
            sum(irate(api_requests_latency_by_status_count{service="{{`{{args.service-name}}`}}",status="200"}[5m]))
          )
{{- end }}
