{{- if .Values.argoRollout.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
spec:
  args:
  - name: query-service-name
  - name: prometheus-address
  - name: query-interval
  - name: success-rate
  - name: metrics-interval
  - name: metrics-count
  - name: metrics-failure-limit
  metrics:
  - name: success-rate
    interval: "{{`{{args.metrics-interval}}`}}"
    count: 5
    successCondition: "result[0] >= 85"
    failureLimit: 2
    provider:
      prometheus:
        address: "{{`{{args.prometheus-address}}`}}"
        query: |
          (
            sum(irate(api_requests_latency_by_status_sum{service="{{`{{args.query-service-name}}`}}",status="200"}[5m])) /
            sum(irate(api_requests_latency_by_status_sum{service="{{`{{args.query-service-name}}`}}"}[5m]))
          ) * 100
{{- end }}
