{{- if and .Values.argoRollout.enabled .Values.argoRollout.notifications.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
data:
  {{- if .Values.argoRollout.notifications.telegram.enabled }}
  service.telegram: |
    token: {{ .Values.argoRollout.notifications.telegram.token }}
  {{- end }}
{{- end }}
