apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-api.fullname" . }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
data:
  service.telegram: |
    token: $telegram-token