{{- if .Values.flaggerCanary.enabled -}}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "flask-api.fullname" . }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
  annotations:
    fluxcd.io/ignore: "false"
spec:
  provider: {{ .Values.flaggerCanary.provider }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "flask-api.fullname" . }}
  {{- if .Values.autoscaling.enabled }}
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: {{ include "flask-api.fullname" . }}
  {{- end }}
  {{- if .Values.ingress.enabled }}
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: {{ include "flask-api.fullname" . }}
  {{- end }}
  service:
    name: {{ include "flask-api.fullname" . }}
    port: {{ .Values.service.port }}
    #portName: http
    targetPort: {{ .Values.service.port }}
    #portDiscovery: true
  skipAnalysis: {{ .Values.flaggerCanary.analysis.skip }}
  metricsServer: {{ .Values.flaggerCanary.metrics.server }}
  analysis:
    {{- .Values.flaggerCanary.analysis.bluegreen | toYaml | nindent 4 }}
    metrics:
      #- name: request-success-rate
      #  query: 
      #  threshold: {{ .Values.flaggerCanary.thresholds.successRate }}
      #  interval: 1m
      - name: request-success-rate
        templateRef:
          name: "{{ include "flask-api.fullname" . }}-request-success-rate"
          namespace: "{{ .Release.Namespace }}" 
        #query: |
        #  ( 
        #    flask_http_request_total{service="{{ include "flask-api.fullname" . }}-canary",status="500"} / 
        #    flask_http_request_total{service="{{ include "flask-api.fullname" . }}-canary",status="200"} 
        #  ) > 0.05
        threshold: 0
        interval: 1m
    webhooks:
      {{- if .Values.flaggerCanary.helmtest.enabled }}
      - name: "helm test"
        type: pre-rollout
        url: {{ .Values.flaggerCanary.helmtest.url }}
        timeout: 3m
        metadata:
          type: "helmv3"
          cmd: "test {{ .Release.Name }} -n {{ .Release.Namespace }}"
      {{- end }}
      {{- if .Values.flaggerCanary.loadtest.enabled }}
      - name: load-test-get
        type: rollout
        url: {{ .Values.flaggerCanary.loadtest.url }}
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 5 -c 2 http://{{ include "flask-api.fullname" . }}-canary.{{ .Release.Namespace }}:{{ .Values.service.port }}"
      {{- end }}
{{- end }}
