{{- if .Values.autoscaling.enabled }}
{{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v1
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "flask-api.fullname" . }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    {{- if .Values.flaggerCanary.enabled }}
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "flask-api.fullname" . }}
    {{- end }}
    {{- if .Values.argoRollout.enabled }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "flask-api.fullname" . }}
    {{- end }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- else -}}
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- end }}
{{- end }}
