{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-api.fullname" . }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "flask-api.fullname" . }}
  endpoints:
  - port: http
    scheme: http
    path: /metrics
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
