{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-api.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "flask-api.selectorLabels" . | nindent 6 }}
  jobLabel: {{ include "flask-api.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: http
    scheme: http
    path: /metrics
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
