{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-api.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
spec:
  selector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - "{{ include "flask-api.fullname" . }}"
      - "{{ include "flask-api.fullname" . }}-primary"
      - "{{ include "flask-api.fullname" . }}-canary"
  #  matchLabels:
  #    {{ include "flask-api.selectorLabels" . | nindent 6 }}
  jobLabel: {{ include "flask-api.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: http
    scheme: http
    path: /metrics
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    interval: {{ .Values.serviceMonitor.interval }}
    relabelings:
    - sourceLabels:
      - '__meta_kubernetes_endpoint_address_target_name'
      regex: '(.*)'
      replacement: '$1'
      targetLabel: container_name
      action: replace
    - sourceLabels:
      - '__meta_kubernetes_endpoints_label_app_kubernetes_io_name'
      regex: '(.*)'
      replacement: '$1'
      targetLabel: app
      action: replace
    - sourceLabels:
      - '__meta_kubernetes_namespace'
      regex: '(.*)'
      replacement: '$1'
      targetLabel: namespace
      action: replace
    - sourceLabels:
      - '__meta_kubernetes_pod_controller_kind'
      regex: '(.*)'
      replacement: '$1'
      targetLabel: kind
      action: replace
    - sourceLabels:
      - '__meta_kubernetes_pod_ip'
      regex: '(.*)'
      replacement: '$1'
      targetLabel: ip
      action: replace
    - sourceLabels:
      - '__meta_kubernetes_pod_label_app_kubernetes_io_name'
      regex: '(.*)'
      replacement: '$1'
      targetLabel: app
      action: replace
    - sourceLabels:
      - '__meta_kubernetes_service_name'
      regex: '(.*)'
      replacement: '$1'
      targetLabel: service
      action: replace
{{- end }}
