---
# https://fluxcd.io/flagger/tutorials/kubernetes-blue-green/

image:
  repository: luismiguelsaez/flask-api
  tag: v2-success

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: api.minikube.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 14s
  namespace: monitoring

argoRollout:
  enabled: true
  analysis:
    enabled: true
    startingStep: 1
    templates:
    - templateName: success-rate
    prometheus:
      address: http://prometheus-kube-prometheus-prometheus.monitoring:9090
  trafficManagement:
    enabled: true
    type: nginx
  steps:
    - setWeight: 5
    - pause: {}

flaggerCanary:
  enabled: false
  provider: nginx
  metrics:
    server: http://prometheus-kube-prometheus-prometheus.monitoring:9090
  analysis:
    skip: false
    bluegreen:
      # schedule interval (default 60s)
      interval: 1m
      # total number of iterations
      iterations: 10
      # max number of failed iterations before rollback
      threshold: 2
  thresholds:
    # minimum req success rate (non 5xx responses)
    # percentage (0-100)
    successRate: 99
    # maximum req duration P99
    # milliseconds
    latency: 500
  loadtest:
    enabled: true
    # load tester address
    url: http://flagger-loadtester.flux-system/
  helmtest:
    enabled: false
    # helm tester address
    url: http://flagger-helmtester.flux-system/
