---
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: api.minikube.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

argoRollout:
  enabled: false
  trafficManagement:
    enabled: true
    type: nginx
  steps:
    - setWeight: 5
    - pause: {}

flaggerCanary:
  enabled: true
  provider: nginx
  metrics:
    server: http://prometheus-kube-prometheus-prometheus.monitoring:9090
  analysis:
    skip: true
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    #maxWeight: 50
    # canary increment step
    # percentage (0-100)
    #stepWeight: 5
    iterations: 1
  thresholds:
    # minimum req success rate (non 5xx responses)
    # percentage (0-100)
    successRate: 99
    # maximum req duration P99
    # milliseconds
    latency: 500
  loadtest:
    enabled: true
    # load tester address
    url: http://flagger-loadtester.flux-system/
  helmtest:
    enabled: false
    # helm tester address
    url: http://flagger-helmtester.flux-system/
